mode:
    mode: 'train'
    multiprocessing_distributed: False
    dist_url: tcp://127.0.0.1:2345
    num_threads: 1
    do_online_eval: True
    parameter_path: ''
train:
    dim_x: 256
    dim_z: 256
    dim_a: ''
    dim_gt: 5
    num_ensemble: 32
    win_size: 5
    seed: 0
    model_name: 'latent_KITTI_v1'
    dataset: 'KITTI_dataset'
    sensor_len: 1
    channel_img_1: 6
    channel_img_2: ''
    input_size_1: ''
    input_size_2: ''
    input_size_3: ''
    data_path: './dataset/KITTI_dataset_train.pkl'
    batch_size: 64
    num_epochs: 50
    learning_rate: 1e-4
    weight_decay: 1e-2
    adam_eps: 1e-3
    log_freq: 20
    eval_freq: 1
    save_freq: 2
    log_directory: './experiments'
    loss: 'mse'
test:
    dim_x: 256
    dim_z: 256
    dim_a: ''
    dim_gt: 5
    num_ensemble: 32
    win_size: 5
    model_name: 'latent_KITTI_v1'
    data_path: './dataset/KITTI_dataset_test.pkl'
    sensor_len: 1
    channel_img_1: 6
    channel_img_2: ''
    input_size_1: ''
    input_size_2: ''
    input_size_3: ''
    checkpoint_path_1: ''
    checkpoint_path_2: ''
    dataset: 'KITTI_dataset'
optim:
    optim: 'adamw'
    lr_scheduler: 'polynomial_decay'