mode:
    mode: 'train'
    multiprocessing_distributed: False
    dist_url: tcp://127.0.0.1:2345
    num_threads: 1
    do_online_eval: True
    parameter_path: ''
train:
    dim_x: 256
    dim_z: 256
    dim_a: 40
    dim_gt: 7
    num_ensemble: 32
    win_size: 3
    seed: 0
    model_name: 'latent_soft'
    dataset: 'soft_robot'
    sensor_len: 3
    channel_img_1: 3
    channel_img_2: 1
    input_size_1: 30
    input_size_2: ''
    input_size_3: ''
    data_path: './dataset/soft_robot_train.pkl'
    batch_size: 64
    num_epochs: 20
    learning_rate: 1e-4
    weight_decay: 1e-2
    adam_eps: 1e-3
    log_freq: 10
    eval_freq: 1
    save_freq: 2
    log_directory: './experiments'
    loss: 'mse'
test:
    dim_x: 256
    dim_z: 256
    dim_a: 40
    dim_gt: 7
    num_ensemble: 32
    win_size: 3
    model_name: 'latent_soft'
    data_path: './dataset/soft_robot_test.pkl'
    sensor_len: 3
    channel_img_1: 3
    channel_img_2: 1
    input_size_1: 30
    input_size_2: ''
    input_size_3: ''
    checkpoint_path_1: ''
    checkpoint_path_2: ''
    dataset: 'soft_robot'
optim:
    optim: 'adamw'
    lr_scheduler: 'polynomial_decay'